theme: minima
title: Welcome to Kevin's Site
author: Kevin Ip
email: kevinwlip@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My Jekyll website hosted on GitHub Pages.
  Plan to update the site with my work.

# social links
github_username:  kevinwlip

show_excerpts: true # set to false to remove excerpts on the homepage
